# ----------------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------------
EXE ?= index
BUILD ?= BUILD_DEBUG

CC := emcc
RUNNER := emrun
COMPILER_FLAGS := -Os -Wall -I/usr/local/include -s USE_GLFW=3 -s ASYNCIFY --preload-file assets --shell-file data/shell.html
SRC_FILES := $(wildcard src/*.c) $(wildcard src/*/*.c) libraylib.a

# ----------------------------------------------------------------------------------
# CONFIG SETUP
# ----------------------------------------------------------------------------------
ifeq ($(BUILD), BUILD_DEBUG)
	COMPILER_FLAGS += -g
    DEFINES += -DBUILD_DEBUG
endif

# ----------------------------------------------------------------------------------
# TARGETS
# ----------------------------------------------------------------------------------
.PHONY: build run clean release

build: $(EXE).html

$(EXE).html: $(SRC_FILES)
	$(CC) -o $@ $^ $(COMPILER_FLAGS)

run: build
	$(RUNNER) $(EXE).html

clean:
	rm -f $(EXE).html $(EXE).wasm $(EXE).js $(EXE).data $(EXE).map

release: build
	zip -r $(EXE).zip $(wildcard $(EXE).*)
